#!/bin/bash
# 查看k8s需要的镜像列表：
kubeadm config images list

#获得k8s初始化参数模板
kubeadm config print init-defaults > init.defaults.yml

# 根据默认配置，做一个配置用于拉依赖镜像：
cp init.defaults.yml init-config-images.yml

# 根据默认配置，做一个配置用于拉依赖镜像：
cat >  init-config-images.yml <<-EOF
apiVersion: kubeadm.k8s.io/v1beta3
imageRepository: registry.aliyuncs.com/google_containers
kind: ClusterConfiguration
kubernetesVersion: 1.22.5
EOF

# 拉取镜像到本地
kubeadm config images pull --config=init-config-images.yml

# 创建默认配置文件
kubeadm config print init-defaults > init-bak.yml

# 编辑默认配置文件
cat > init.yml <<-EOF
# 版本修改
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  # 修改
  advertiseAddress: 192.168.16.4
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  imagePullPolicy: IfNotPresent
  # 修改
  name: k8s-master
  taints: null
---
apiServer:
  timeoutForControlPlane: 4m0s
# 版本修改
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
# 修改
imageRepository: registry.aliyuncs.com/google_containers
kind: ClusterConfiguration
kubernetesVersion: 1.22.0
networking:
  dnsDomain: cluster.local
  # 修改
  serviceSubnet: 10.96.0.0/12
  # 修改
  podSubnet: 10.244.0.0/16
scheduler: {}
EOF


